In [160]:
import numpy as np
import pandas as pd

In [165]:

d = 5
set_x = 'random'
num_p = 500

In [184]:
df = pd.read_csv('qing_sd_metod_beta_%s_m=%s_d=%s'
                    '_%s_%s.csv'
                       % (beta, m, d, set_x,
                          num_p))
store_ex_des = df['number_extra_descents_per_func_metod']
store_minima = np.array(df['number_minimas_per_func_multistart'])
store_minima_metod = np.array(df['number_minimas_per_func_metod'])
store_time_metod = np.array(df['time_metod'])
store_time_multistart= np.array(df['time_multistart'])
no_its = np.genfromtxt('qing_no_its_mult_beta_%s_m=%s_d=%s_%s_%s.csv' %
                        (beta, m, d, set_x, num_p), delimiter=',')

In [185]:
np.mean(np.array(store_ex_des))

19.0

In [186]:
np.mean(store_time_metod) / np.mean(store_time_multistart)

0.2656179886912431

In [187]:
np.mean(store_time_metod)

5.407809019088745

In [188]:
np.mean(store_time_multistart)

20.359347820281986

In [189]:
store_minima

array([32.])

In [190]:
store_minima_metod

array([32.])

In [192]:
no_its

array([25., 17., 23., 18., 15., 14., 25., 22., 14., 14., 22., 18., 15.,
       20., 15., 18., 16., 20., 17., 19., 16., 26., 27., 23., 25., 23.,
       19., 23., 11., 19., 19., 18., 18., 19., 33., 20., 20., 18., 23.,
       36., 15., 20., 17., 19., 20., 16., 14., 25., 15., 17., 19., 16.,
       19., 22., 20., 15., 19., 14., 22., 20., 21., 19., 20., 13., 20.,
       23., 20., 18., 18., 19., 16., 17., 27., 29., 19., 19., 22., 20.,
       19., 19., 20., 28., 20., 17., 16., 31., 20., 24., 20., 15., 19.,
       18., 18., 17., 41., 28., 20., 20., 15., 15., 15., 14., 16., 17.,
       23., 15., 12., 18., 15., 29., 18., 20., 36., 17., 17., 19., 15.,
       13., 15., 13., 18., 27., 27., 17., 18., 20., 23., 26., 15., 18.,
       45., 18., 23., 22., 22., 13., 23., 20., 21., 18., 21., 19., 16.,
       17., 14., 17., 39., 23., 16., 22., 21., 20., 21., 20., 16., 17.,
       17., 20., 26., 15., 18., 20., 20., 12., 34., 17., 21., 32., 16.,
       14., 20., 13., 17., 22., 19., 28., 17., 17., 26., 44., 16

In [3]:
import metod as mt
from metod import objective_functions as mt_obj
from metod import metod_algorithm_functions as mt_alg
import pytest

In [4]:
def func_params(d=20, p=2, lambda_1=1, lambda_2=10):
    """Generates parameters to use for tests."""
    f = mt_obj.several_quad_function
    g = mt_obj.several_quad_gradient
    store_x0, matrix_test = (mt_obj.function_parameters_several_quad(p, d, 
                             lambda_1, lambda_2))
    func_args = p, store_x0, matrix_test
    return f, g, func_args

In [11]:
np.random.seed(20)
lambda_1 = 1
lambda_2 = 10
p = 10
d = 20
num_points = 100
store_x0, matrix_test = (mt_obj.function_parameters_several_quad
                         (p, d, lambda_1, lambda_2))
func_args = p, store_x0, matrix_test
f = mt_obj.several_quad_function
g = mt_obj.several_quad_gradient
tolerance = 0.00001
projection = False
starting_points = np.random.uniform(0, 1, (num_points, d))
const = 0.1
met = 'None'
option = 'forward_backward_tracking'
initial_guess = 0.005
bounds_set_x = (0, 1)
relax_sd_it = 1
(unique_minimizers_mult,
 unique_number_of_minimizers_mult,
 store_func_vals_mult,
 time_taken_des,
 store_minimizer_des) = mt.multistart(f, g, func_args, d, starting_points,
                                      num_points, tolerance, projection,
                                      const, option, met, initial_guess,
                                      bounds_set_x, relax_sd_it)
"""Check outputs are as expected"""
assert(len(unique_minimizers_mult) == unique_number_of_minimizers_mult)
assert(unique_number_of_minimizers_mult == len(store_func_vals_mult))

"""Ensure that each region of attraction discovered is unique"""
mt_obj.check_unique_minimizers(store_minimizer_des,
                               unique_number_of_minimizers_mult,
                               mt_obj.calc_minimizer_sev_quad, func_args)
assert(time_taken_des >= 0)

100%|████████████████████████████████████████████████████████████████████████████████| 100/100 [00:42<00:00,  2.34it/s]
